/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.myapp;

/**
 *
 * @author informatics
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ShowName = new javax.swing.JMenuItem();
        ShowColl = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuShowCondition = new javax.swing.JMenuItem();
        menuShowAdd = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("ฐานข้อมูล");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        ShowName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowName.setText("แสดงชื่อฐานข้อมูล");
        ShowName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowNameActionPerformed(evt);
            }
        });
        jMenu1.add(ShowName);

        ShowColl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ShowColl.setText("แสดงชื่อ Collection");
        ShowColl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowCollActionPerformed(evt);
            }
        });
        jMenu1.add(ShowColl);

        Exit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("จัดการข้อมูลผู้ใช้");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        menuShowCondition.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuShowCondition.setText("แสดงข้อมูลแบบเงื่อนไข");
        menuShowCondition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShowConditionActionPerformed(evt);
            }
        });
        jMenu2.add(menuShowCondition);

        menuShowAdd.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        menuShowAdd.setText("เพิ่มข้อมูล");
        menuShowAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuShowAddActionPerformed(evt);
            }
        });
        jMenu2.add(menuShowAdd);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    private void ShowNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowNameActionPerformed
        ShowDB showName = new ShowDB();
        showName.setVisible(true);
    }//GEN-LAST:event_ShowNameActionPerformed

    private void ShowCollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowCollActionPerformed
        ShowCollection showCollection = new ShowCollection();
        showCollection.setVisible(true);
    }//GEN-LAST:event_ShowCollActionPerformed

    private void menuShowConditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShowConditionActionPerformed
        // TODO add your handling code here:
        ShowDocumentCondition from2 = new ShowDocumentCondition();
        from2.setVisible(true);
    }//GEN-LAST:event_menuShowConditionActionPerformed

    private void menuShowAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuShowAddActionPerformed
        // TODO add your handling code here:
        AddDocument from2 = new AddDocument();
        from2.setVisible(true);
    }//GEN-LAST:event_menuShowAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem ShowColl;
    private javax.swing.JMenuItem ShowName;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem menuShowAdd;
    private javax.swing.JMenuItem menuShowCondition;
    // End of variables declaration//GEN-END:variables
}
